CREATE DATABASE Blog
GO

USE Blog 

CREATE TABLE Category
(
	Id INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	CategoryName NVARCHAR(20) NOT NULL 
)

CREATE TABLE News
(
	Id INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	ShortDesc NVARCHAR(1000) NOT NULL,
	Description NVARCHAR(MAX) NOT NULL,
	ImageLink NVARCHAR(500),
	CategoryID INT NOT NULL DEFAULT '1',
	Tags NVARCHAR(400) NOT NULL,
	Date DATETIME2 
	CONSTRAINT FK_Category FOREIGN KEY(CategoryID) REFERENCES Category (Id) ON DELETE SET DEFAULT ON UPDATE CASCADE
)
